version: "3"

services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - city_opt_api
    networks:
      - frontend

  city_opt_api:
    build: ./city_opt_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - backend

  optimization_worker:
    build: ./optimization_worker
    depends_on:
      - rabbitmq
    scale:
      workers: 3
    networks:
      - backend

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  frontend:
  backend: